In [1]:
import sqlite3
import pandas as pd

# 1. Connect to the local database file
# If the file is in your current folder, just use the name
conn = sqlite3.connect('db.sqlite3')

# 2. Write your query
query = "SELECT * FROM pmjay_fraud_dashboard_app_last24hour"

# 3. Read into DataFrame
df = pd.read_sql_query(query, conn)
df

,id,registration_id,case_id,member_id,family_id,patient_name,patient_dob,patient_state_code,patient_district_code,patient_district_name,...,current_workflow_role,current_workflow_user,service_request_type,m_flag,careplan_desc,discharge_type,admission_type,claim_approved_date,last_insert_dt,admission_dt
0,1764599,1014722636,BOCW/BR/2025/R2/1014722636,ML7DSMT2X,10BO102290138724457200000105,Surendra Prasad,1959,10,209,NALANDA,...,None,None,None,None,None,nan,P,2025-11-07 11:19:40.347000,2025-11-09 22:20:02.947000,2025-10-04 11:09:00
1,1764600,1015196657,BOCW/BR/2025/R2/1015196657,MRI5GRVS0,10BO10020130025006400074,Soni Khatoon,1982,10,213,PURBI CHAMPARAN,...,None,None,None,None,None,nan,E,2025-11-08 14:10:45.025000,2025-11-08 14:00:05.009000,2025-10-13 00:00:00
2,1764601,1015487177,BOCW/BR/2025/R2/1015487177,MM518DRJ1,10BO10100040120014200014,DHANIYL TUDDU,2009,10,201,KATIHAR,...,None,None,None,None,None,nan,P,2025-11-08 22:16:11.302000,2025-11-08 22:20:03.246000,2025-10-18 11:21:00
3,1764602,1015568572,BOCW/BR/2025/R2/1015568572,MQPWPFNQW,10BO102260135880135810016910,Radhika Devi,1995,10,207,MUNGER,...,None,None,None,None,None,nan,P,2025-11-07 16:01:01.663000,2025-11-09 22:20:02.947000,2025-10-21 00:00:00
4,1764603,1015620395,BOCW/BR/2025/R2/1015620395,P13L8Z8SM,10BO102320144524883300000304,Chandan Pandit,1991,10,194,BUXAR,...,None,None,None,None,None,nan,P,2025-11-08 22:16:11.408000,2025-11-08 22:20:03.246000,2025-10-22 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93395,1857994,1015575441,PMJAY/BR/S/G/2025/R2/1015575441,MK1GR7Z2W,10PH10180110130031200049,Nagdev Ray,1953,10,224,VAISHALI,...,None,None,None,None,None,nan,P,2025-11-04 11:34:24.841000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00
93396,1857995,1015575450,PMJAY/BR/S/G/2025/R2/1015575450,MS490ZEO7,10PH10070080101033809994,REHALA PERWEEN,2000,10,188,ARARIA,...,None,None,None,None,None,nan,E,2025-11-06 00:12:58.167000,2025-11-06 00:20:02.612000,2025-10-18 19:00:00
93397,1857996,1015575467,PMJAY/BR/S/G/2025/R2/1015575467,MKVCD505J,10PH10250030138043800015,RANJEET KUMAR,1998,10,204,LAKHISARAI,...,None,None,None,None,None,nan,P,2025-11-02 22:15:32.192000,2025-11-03 17:20:03.577000,2025-10-21 16:31:00
93398,1857997,1015575484,PMJAY/BR/S/G/2025/R2/1015575484,PN6RMHVX1,10PH10020120003002100121,Vasudev Sah,1955,10,213,PURBI CHAMPARAN,...,None,None,None,None,None,nan,P,2025-11-04 11:33:39.509000,2025-11-04 11:40:02.738000,2025-10-22 00:00:00
93399,1857998,1015575486,PMJAY/BR/S/G/2025/R2/1015575486,MLPUPSLJZ,10PH10330100110017400030,Ranjeet Kumar,1995,10,189,AURANGABAD,...,None,None,None,None,None,nan,P,2025-11-04 11:32:08.310000,2025-11-04 11:40:02.738000,2025-10-21 16:00:00

In [3]:
df['amount_claim_initiated'].count()

np.int64(84741)

In [4]:
df1 = df

In [5]:
df1['only_date'] = pd.to_datetime(df1['preauth_init_date'], format="mixed").dt.date
df1['only_date'].value_counts()

only_date
2025-10-13    5375
2025-10-08    5240
2025-10-14    5140
2025-10-06    5135
2025-10-09    5013
2025-10-07    5012
2025-10-10    4799
2025-10-15    4783
2025-10-16    4735
2025-10-11    4494
2025-10-17    4179
2025-10-30    3889
2025-10-31    3495
2025-10-18    3421
2025-10-04    3258
2025-10-03    2978
2025-10-21    2764
2025-10-29    2680
2025-10-12    2264
2025-10-05    1973
2025-10-22    1575
2025-10-23    1569
2025-10-24    1506
2025-10-01    1495
2025-10-19    1353
2025-10-25    1352
2025-10-28    1028
2025-10-02     988
2025-10-20     846
2025-10-26     583
2025-10-27     478
Name: count, dtype: int64

In [6]:
df3 = df1[(df1['hospital_type'] == 'P') & (df1['case_type'] == 'SURGICAL') & (df1['amount_claim_initiated'] >= 100000)]
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 351 entries, 22 to 92775
Data columns (total 76 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        351 non-null    int64
 1   registration_id           351 non-null    object
 2   case_id                   351 non-null    object
 3   member_id                 351 non-null    object
 4   family_id                 351 non-null    object
 5   patient_name              351 non-null    object
 6   patient_dob               351 non-null    object
 7   patient_state_code        351 non-null    object
 8   patient_district_code     351 non-null    object
 9   patient_district_name     351 non-null    object
 10  patient_state_name        351 non-null    object
 11  gender                    351 non-null    object
 12  age                       351 non-null    int64
 13  policy_code               351 non-null    object
 14  renewal_code              351 non-null    object
 15  category_details          351 non-null    object
 16  speciality_code           351 non-null    object
 17  procedure_details         351 non-null    object
 18  procedure_code            351 non-null    object
 19  case_type                 351 non-null    object
 20  status_id_pk              351 non-null    object
 21  case_status               0 non-null      object
 22  hospital_id               351 non-null    object
 23  hospital_name             351 non-null    object
 24  hosp_district_name        351 non-null    object
 25  hosp_state_name           351 non-null    object
 26  hospital_state_cd         351 non-null    object
 27  hospital_district_cd      351 non-null    object
 28  hosp_pan_number           351 non-null    object
 29  hospital_type             351 non-null    object
 30  preauth_init_date         351 non-null    object
 31  amount_preauth_initiated  351 non-null    float64
 32  preauth_approved_date     351 non-null    object
 33  amount_preauth_approved   351 non-null    float64
 34  preauth_rejected_date     351 non-null    object
 35  surgery_dt                351 non-null    object
 36  death_dt                  351 non-null    object
 37  discharge_dt              351 non-null    object
 38  claim_init_date           351 non-null    object
 39  amount_claim_initiated    351 non-null    float64
 40  amount_claim_approved     344 non-null    float64
 41  amount_claim_paid         305 non-null    float64
 42  claim_rejected_date       351 non-null    object
 43  rf_amount                 0 non-null      object
 44  tds_amount                212 non-null    float64
 45  utr_no                    351 non-null    object
 46  payment_paid_dt           351 non-null    object
 47  transaction_amount        212 non-null    float64
 48  cpd_approved_date         351 non-null    object
 49  cpd_approved_amount       319 non-null    float64
 50  cpd_user                  351 non-null    object
 51  aco_approved_date         351 non-null    object
 52  aco_approved_amount       314 non-null    float64
 53  aco_user                  351 non-null    object
 54  sha_approved_date         351 non-null    object
 55  sha_approved_amount       308 non-null    float64
 56  sha_user                  351 non-null    object
 57  json_object_perauth       0 non-null      object
 58  json_object_claim         0 non-null      object
 59  json_object_ben           0 non-null      object
 60  src_account_no            0 non-null      object
 61  src_ifsc_code             0 non-null      object
 62  paid_flag                 0 non-null      object
 63  hosp_account_number       0 non-null      object
 64  ben_ifsc_code             0 non-null      object
 65  current_workflow_role     0 non-null      object
 66  current_workflow_user     0 non-null      object
 67  service_request_type      0 non-null      object
 68  m_flag                    0 non-null      object
 69  careplan_desc             0 non-null      object
 70  discharge_type            351 non-null    object
 71  admission_type            351 non-null    object
 72  claim_approved_date       351 non-null    object
 73  last_insert_dt            351 non-null    object
 74  admission_dt              351 non-null    object
 75  only_date                 351 non-null    object
dtypes: float64(10), int64(2), object(64)
memory usage: 211.1+ KB

In [7]:
df3['amount_claim_initiated']

22       147000.0
90       248445.0
276      117600.0
853      122500.0
924      248050.0
           ...
90125    277640.0
92138    147000.0
92444    226460.0
92743    130070.0
92775    100430.0
Name: amount_claim_initiated, Length: 351, dtype: float64

In [44]:
df2 = pd.read_excel("high_value_claims_excel_report.xlsx")
df2.info()

FileNotFoundError: [Errno 2] No such file or directory: 'high_value_claims_excel_report.xlsx'

In [45]:
df3[~df3['registration_id'].isin(df2['Claim ID'].astype(str))]['amount_claim_initiated'].unique()

NameError: name 'df2' is not defined

### High Value Claims

In [ ]:
df3[~df3['registration_id'].isin(df2['Claim ID'].astype(str))]['amount_claim_initiated']

Series([], Name: amount_claim_initiated, dtype: float64)

### Family ID Cases

In [8]:
df1['family_id']

0        10BO102290138724457200000105
1            10BO10020130025006400074
2            10BO10100040120014200014
3        10BO102260135880135810016910
4        10BO102320144524883300000304
                     ...
93395        10PH10180110130031200049
93396        10PH10070080101033809994
93397        10PH10250030138043800015
93398        10PH10020120003002100121
93399        10PH10330100110017400030
Name: family_id, Length: 93400, dtype: object

In [9]:
# Family cases are taken only for private hospitals

df1['preauth_init_date'] = pd.to_datetime(df1['preauth_init_date'], format='mixed')
df1['temp_date'] = df1['preauth_init_date'].dt.date
counts = df1.groupby(['temp_date', 'family_id', 'hospital_type']).size().reset_index(name='daily_count')
duplicates = counts[counts['daily_count'] > 1]
duplicates[duplicates['hospital_type'] == 'P'].nunique()

temp_date          31
family_id        1443
hospital_type       1
daily_count         5
dtype: int64

### Geographic Anomalies

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93400 entries, 0 to 93399
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        93400 non-null  int64
 1   registration_id           93400 non-null  object
 2   case_id                   93400 non-null  object
 3   member_id                 93400 non-null  object
 4   family_id                 93400 non-null  object
 5   patient_name              93400 non-null  object
 6   patient_dob               93400 non-null  object
 7   patient_state_code        93400 non-null  object
 8   patient_district_code     93400 non-null  object
 9   patient_district_name     93400 non-null  object
 10  patient_state_name        93400 non-null  object
 11  gender                    93400 non-null  object
 12  age                       93400 non-null  int64
 13  policy_code               93400 non-null  object
 14  renewal_code              93400 non-null  object
 15  category_details          93400 non-null  object
 16  speciality_code           93400 non-null  object
 17  procedure_details         93400 non-null  object
 18  procedure_code            93400 non-null  object
 19  case_type                 93400 non-null  object
 20  status_id_pk              93400 non-null  object
 21  case_status               0 non-null      object
 22  hospital_id               93400 non-null  object
 23  hospital_name             93400 non-null  object
 24  hosp_district_name        93400 non-null  object
 25  hosp_state_name           93400 non-null  object
 26  hospital_state_cd         93400 non-null  object
 27  hospital_district_cd      93400 non-null  object
 28  hosp_pan_number           93400 non-null  object
 29  hospital_type             93400 non-null  object
 30  preauth_init_date         93400 non-null  datetime64[ns]
 31  amount_preauth_initiated  93400 non-null  float64
 32  preauth_approved_date     93400 non-null  object
 33  amount_preauth_approved   93394 non-null  float64
 34  preauth_rejected_date     93400 non-null  object
 35  surgery_dt                93400 non-null  object
 36  death_dt                  93400 non-null  object
 37  discharge_dt              93400 non-null  object
 38  claim_init_date           93400 non-null  object
 39  amount_claim_initiated    84741 non-null  float64
 40  amount_claim_approved     83313 non-null  float64
 41  amount_claim_paid         77263 non-null  float64
 42  claim_rejected_date       93400 non-null  object
 43  rf_amount                 0 non-null      object
 44  tds_amount                47015 non-null  float64
 45  utr_no                    93400 non-null  object
 46  payment_paid_dt           93400 non-null  object
 47  transaction_amount        55056 non-null  float64
 48  cpd_approved_date         93400 non-null  object
 49  cpd_approved_amount       79224 non-null  float64
 50  cpd_user                  93400 non-null  object
 51  aco_approved_date         93400 non-null  object
 52  aco_approved_amount       78909 non-null  float64
 53  aco_user                  93400 non-null  object
 54  sha_approved_date         93400 non-null  object
 55  sha_approved_amount       77415 non-null  float64
 56  sha_user                  93400 non-null  object
 57  json_object_perauth       0 non-null      object
 58  json_object_claim         0 non-null      object
 59  json_object_ben           0 non-null      object
 60  src_account_no            0 non-null      object
 61  src_ifsc_code             0 non-null      object
 62  paid_flag                 0 non-null      object
 63  hosp_account_number       0 non-null      object
 64  ben_ifsc_code             0 non-null      object
 65  current_workflow_role     0 non-null      object
 66  current_workflow_user     0 non-null      object
 67  service_request_type      0 non-null      object
 68  m_flag                    0 non-null      object
 69  careplan_desc             0 non-null      object
 70  discharge_type            93400 non-null  object
 71  admission_type            93400 non-null  object
 72  claim_approved_date       93400 non-null  object
 73  last_insert_dt            93400 non-null  object
 74  admission_dt              93373 non-null  object
 75  only_date                 93400 non-null  object
 76  temp_date                 93400 non-null  object
dtypes: datetime64[ns](1), float64(10), int64(2), object(64)
memory usage: 54.9+ MB

In [11]:
df1[(df1['patient_state_name'] != df1['hosp_state_name']) & (df1['hospital_type'] == 'P')]

,id,registration_id,case_id,member_id,family_id,patient_name,patient_dob,patient_state_code,patient_district_code,patient_district_name,...,service_request_type,m_flag,careplan_desc,discharge_type,admission_type,claim_approved_date,last_insert_dt,admission_dt,only_date,temp_date
24,1764623,1015140976,PMJAY/BR/S/G/2025/R2/1015140976,MKLGS5JSU,10PH10310080239038810006,Jiut Pasawan,1949,10,200,KAIMUR (BHABUA),...,None,None,None,nan,E,2025-11-07 15:24:49.067000,2025-11-09 11:20:03.078000,2025-10-12 00:00:00,2025-10-14,2025-10-14
33,1764632,1015341884,PMJAY/BR/S/G/2025/R2/1015341884,MS40D6FEK,10VVS10230100002000200022,Mankawa Devi,1943,10,190,BANKA,...,None,None,None,nan,P,2025-11-09 16:06:48.926000,2025-11-09 16:00:04.540000,2025-10-15 00:00:00,2025-10-15,2025-10-15
90,1764689,1015770111,PMJAY/BR/S/G/2025/R2/1015770111,MS4B8KNOG,10S102800900030000000510011,GANGA RISHI,1981,10,188,ARARIA,...,None,None,None,nan,E,2025-11-09 20:02:32.320000,2025-11-09 20:00:03.410000,2025-10-25 00:00:00,2025-10-25,2025-10-25
95,1764694,1015791112,PMJAY/BR/S/G/2025/R2/1015791112,MS4BCXZ3N,10S102800170930009002410118,CHAMPA DEVI,1980,10,212,PATNA,...,None,None,None,nan,E,2025-11-09 18:41:12.910000,2025-11-09 18:40:02.821000,2025-10-26 00:00:00,2025-10-26,2025-10-26
97,1764696,1015821836,PMJAY/BR/S/G/2025/R2/1015821836,MS4BX4Y2S,10S101501200720000034800100,ASHIQ HUSAIN,1967,10,195,DARBHANGA,...,None,None,None,nan,P,2025-11-09 18:41:12.887000,2025-11-09 18:40:02.821000,2025-10-27 00:00:00,2025-10-27,2025-10-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93383,1857982,1015575306,PMJAY/BR/S/G/2025/R2/1015575306,MMZ3VAY65,10VVS10VVS1132144400,Ramnath Sah,1950,10,197,GOPALGANJ,...,None,None,None,nan,E,2025-11-04 11:36:22.281000,2025-11-04 11:40:02.738000,2025-10-21 17:39:00,2025-10-21,2025-10-21
93384,1857983,1015575314,PMJAY/BR/S/G/2025/R2/1015575314,PX8W9MEFK,10PH10240060061012700169,Chhatish Singh,1975,10,207,MUNGER,...,None,None,None,nan,P,2025-11-02 22:15:56.946000,2025-11-03 17:20:03.577000,2025-10-21 00:00:00,2025-10-21,2025-10-21
93387,1857986,1015575345,PMJAY/BR/S/G/2025/R2/1015575345,P1R2HB63R,10PH10040160032030100116,Shakina Khatoon,1973,10,221,SITAMARHI,...,None,None,None,nan,P,2025-11-02 22:16:27.781000,2025-11-03 17:20:03.577000,2025-10-21 00:00:00,2025-10-21,2025-10-21
93391,1857990,1015575405,PMJAY/BR/S/G/2025/R2/1015575405,MKO4FYTUV,10PH102340145825074600000248,KINU CHAUDHARI,2004,10,215,ROHTAS,...,None,None,None,nan,P,2025-11-02 22:14:53.339000,2025-11-03 17:20:03.577000,2025-10-21 00:00:00,2025-10-21,2025-10-21
93394,1857993,1015575439,PMJAY/BR/S/G/2025/R2/1015575439,MK1M1UZN0,10PH10310080213016100049,NATHUNI BIND,1958,10,200,KAIMUR (BHABUA),...,None,None,None,nan,E,2025-11-04 11:34:52.768000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22

### Opthalmology

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93400 entries, 0 to 93399
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        93400 non-null  int64
 1   registration_id           93400 non-null  object
 2   case_id                   93400 non-null  object
 3   member_id                 93400 non-null  object
 4   family_id                 93400 non-null  object
 5   patient_name              93400 non-null  object
 6   patient_dob               93400 non-null  object
 7   patient_state_code        93400 non-null  object
 8   patient_district_code     93400 non-null  object
 9   patient_district_name     93400 non-null  object
 10  patient_state_name        93400 non-null  object
 11  gender                    93400 non-null  object
 12  age                       93400 non-null  int64
 13  policy_code               93400 non-null  object
 14  renewal_code              93400 non-null  object
 15  category_details          93400 non-null  object
 16  speciality_code           93400 non-null  object
 17  procedure_details         93400 non-null  object
 18  procedure_code            93400 non-null  object
 19  case_type                 93400 non-null  object
 20  status_id_pk              93400 non-null  object
 21  case_status               0 non-null      object
 22  hospital_id               93400 non-null  object
 23  hospital_name             93400 non-null  object
 24  hosp_district_name        93400 non-null  object
 25  hosp_state_name           93400 non-null  object
 26  hospital_state_cd         93400 non-null  object
 27  hospital_district_cd      93400 non-null  object
 28  hosp_pan_number           93400 non-null  object
 29  hospital_type             93400 non-null  object
 30  preauth_init_date         93400 non-null  datetime64[ns]
 31  amount_preauth_initiated  93400 non-null  float64
 32  preauth_approved_date     93400 non-null  object
 33  amount_preauth_approved   93394 non-null  float64
 34  preauth_rejected_date     93400 non-null  object
 35  surgery_dt                93400 non-null  object
 36  death_dt                  93400 non-null  object
 37  discharge_dt              93400 non-null  object
 38  claim_init_date           93400 non-null  object
 39  amount_claim_initiated    84741 non-null  float64
 40  amount_claim_approved     83313 non-null  float64
 41  amount_claim_paid         77263 non-null  float64
 42  claim_rejected_date       93400 non-null  object
 43  rf_amount                 0 non-null      object
 44  tds_amount                47015 non-null  float64
 45  utr_no                    93400 non-null  object
 46  payment_paid_dt           93400 non-null  object
 47  transaction_amount        55056 non-null  float64
 48  cpd_approved_date         93400 non-null  object
 49  cpd_approved_amount       79224 non-null  float64
 50  cpd_user                  93400 non-null  object
 51  aco_approved_date         93400 non-null  object
 52  aco_approved_amount       78909 non-null  float64
 53  aco_user                  93400 non-null  object
 54  sha_approved_date         93400 non-null  object
 55  sha_approved_amount       77415 non-null  float64
 56  sha_user                  93400 non-null  object
 57  json_object_perauth       0 non-null      object
 58  json_object_claim         0 non-null      object
 59  json_object_ben           0 non-null      object
 60  src_account_no            0 non-null      object
 61  src_ifsc_code             0 non-null      object
 62  paid_flag                 0 non-null      object
 63  hosp_account_number       0 non-null      object
 64  ben_ifsc_code             0 non-null      object
 65  current_workflow_role     0 non-null      object
 66  current_workflow_user     0 non-null      object
 67  service_request_type      0 non-null      object
 68  m_flag                    0 non-null      object
 69  careplan_desc             0 non-null      object
 70  discharge_type            93400 non-null  object
 71  admission_type            93400 non-null  object
 72  claim_approved_date       93400 non-null  object
 73  last_insert_dt            93400 non-null  object
 74  admission_dt              93373 non-null  object
 75  only_date                 93400 non-null  object
 76  temp_date                 93400 non-null  object
dtypes: datetime64[ns](1), float64(10), int64(2), object(64)
memory usage: 54.9+ MB

In [13]:
df1['preauth_hour'] = pd.to_datetime(df1['preauth_init_date'], format='mixed').dt.hour
df1['preauth_hour']

0        11
1        12
2        17
3        14
4        19
         ..
93395     4
93396    12
93397    16
93398    13
93399    15
Name: preauth_hour, Length: 93400, dtype: int32

In [14]:
df1['procedure_code'].value_counts()

procedure_code
SE020A                                                            26456
MG072D                                                            13965
ER003A                                                             5860
SG039C                                                             3002
SE014A                                                             1693
                                                                  ...
MG001A|MG001A|MG001A|MG004A|MG004A|MG004A|MG021A|MG021A|MG021A        1
SG075B|SG091A                                                         1
SB052A|SB053A|SB070B|SB071A                                           1
MP001A|MP001A|MP001A|MP001D                                           1
MO001A|MO002A|MO053A|MO071F                                           1
Name: count, Length: 5931, dtype: int64

In [15]:
df1['category_details'].value_counts()

category_details
Opthalmology                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      30358
General Medicine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  16065
General Surgery                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    7579
Emergency Room Packages (Care requiring less than 12 hrs stay)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     6009
Medical Oncology                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   4932
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ...
Medical Oncology|Medical Oncology|Medical Oncology|Medical Oncology|Radiation Oncology|Radiation Oncology                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
Emergency Room Packages (Care requiring less than 12 hrs stay)|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine        1
Emergency Room Packages (Care requiring less than 12 hrs stay)|General Medicine|General Medicine|General Medicine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Obstetrics & Gynaecology|Obstetrics & Gynaecology|Obstetrics & Gynaecology|Obstetrics & Gynaecology|Obstetrics & Gynaecology                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
Emergency Room Packages (Care requiring less than 12 hrs stay)|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|General Medicine|Polytrauma                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Name: count, Length: 655, dtype: int64

In [16]:
df1[(df1['hospital_type'] == 'P') & (df1['procedure_code'].str.contains('SE', na=False))]['category_details'].value_counts()

category_details
Opthalmology                                                                       29974
Opthalmology|Opthalmology                                                            957
Opthalmology|Opthalmology|Opthalmology                                                15
Otorhinolaryngology|Otorhinolaryngology|Otorhinolaryngology                            7
General Surgery|General Surgery                                                        4
Opthalmology|Opthalmology|Opthalmology|Opthalmology                                    3
General Surgery|General Surgery|General Surgery                                        2
General Surgery|Otorhinolaryngology|Otorhinolaryngology                                1
Medical Oncology                                                                       1
Otorhinolaryngology|Otorhinolaryngology|Otorhinolaryngology|Otorhinolaryngology        1
Name: count, dtype: int64

In [17]:
df1[(df1['hospital_type'] == 'P') & (df1['category_details'].str.contains('Opthalmology', na=False))]['category_details'].value_counts()

category_details
Opthalmology                                           29974
Opthalmology|Opthalmology                                957
Opthalmology|Opthalmology|Opthalmology                    15
Opthalmology|Opthalmology|Opthalmology|Opthalmology        3
Name: count, dtype: int64

In [18]:
df1[(df1['hospital_type'] == 'P') & (df1['procedure_code'].str.contains('SE', na=False)) & (df1['age'] < 40)]

,id,registration_id,case_id,member_id,family_id,patient_name,patient_dob,patient_state_code,patient_district_code,patient_district_name,...,m_flag,careplan_desc,discharge_type,admission_type,claim_approved_date,last_insert_dt,admission_dt,only_date,temp_date,preauth_hour
3,1764602,1015568572,BOCW/BR/2025/R2/1015568572,MQPWPFNQW,10BO102260135880135810016910,Radhika Devi,1995,10,207,MUNGER,...,None,None,nan,P,2025-11-07 16:01:01.663000,2025-11-09 22:20:02.947000,2025-10-21 00:00:00,2025-10-21,2025-10-21,14
20,1764619,1014992144,PMJAY/BR/S/G/2025/R2/1014992144,MLF74R6DC,10AAY10030050002001300058,NARESH PASWAN,1993,10,220,SHEOHAR,...,None,None,nan,P,2025-11-08 22:14:03.083000,2025-11-08 22:20:03.246000,2025-10-08 17:01:00,2025-10-08,2025-10-08,23
27,1764626,1015215111,PMJAY/BR/S/G/2025/R2/1015215111,PZPTK6OW2,10PH10100040174041700026,Sabina Khatoon,1991,10,201,KATIHAR,...,None,None,nan,P,2025-11-08 15:13:47.030000,2025-11-08 15:20:04.198000,2025-10-13 13:34:00,2025-10-14,2025-10-14,11
63,1764662,1015616229,PMJAY/BR/S/G/2025/R2/1015616229,MLDWMCKXW,10AAY10280150002002000057,Samti Devi,1991,10,212,PATNA,...,None,None,nan,P,NaT,2025-11-09 14:00:03.544000,2025-10-22 17:30:00,2025-10-22,2025-10-22,17
111,1764710,1015975085,PMJAY/BR/S/G/2025/R2/1015975085,MMIBEL2YA,10PH10110050002004000017,SARITA KUMARI,2010,10,205,MADHEPURA,...,None,None,nan,P,2025-11-08 22:13:45.886000,2025-11-08 22:20:03.246000,2025-10-29 00:00:00,2025-10-30,2025-10-30,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91070,1855669,1015523187,PMJAY/BR/S/G/2025/R2/1015523187,ML7UWUR69,10PH102300141524629200001034,AJIT KUMAR,1988,10,212,PATNA,...,None,None,nan,P,2025-11-01 22:32:31.347000,2025-11-03 17:20:03.577000,2025-10-19 00:00:00,2025-10-19,2025-10-19,18
92072,1856671,1015553388,PMJAY/BR/S/G/2025/R2/1015553388,MS1IC20EX,10PH102280137724404800000228,Guddi Kumari,1993,10,219,SHEIKHPURA,...,None,None,nan,P,2025-11-02 22:15:24.300000,2025-11-03 17:20:03.577000,2025-10-21 11:06:00,2025-10-21,2025-10-21,11
92090,1856689,1015553752,PMJAY/BR/S/G/2025/R2/1015553752,MS46HLYRW,10PH102070108822011100000410,Sanjeev Kumar Nirala,1992,10,206,MADHUBANI,...,None,None,nan,P,NaT,2025-10-22 19:40:02.501000,2025-10-21 13:00:00,2025-10-22,2025-10-22,19
92170,1856769,1015555112,PMJAY/BR/S/G/2025/R2/1015555112,MQPKT0RBX,10PH10140070154054210139,Md Tanweer Alam,1994,10,208,MUZAFFARPUR,...,None,None,nan,P,2025-11-04 11:36:38.317000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-21,2025-10-21,11
93010,1857609,1015568963,PMJAY/BR/S/G/2025/R2/1015568963,MS43W9BKJ,10PH10170120017004500009,Manejar Ray,1990,10,218,SARAN,...,None,None,nan,P,2025-11-05 19:13:55.632000,2025-11-05 19:20:03.212000,2025-10-21 00:00:00,2025-10-23,2025-10-23,14

In [19]:
df1[(df1['hospital_type'] == 'P') & (df1['category_details'].str.contains('Opthalmology', na=False)) & (df1['age'] < 40)]

,id,registration_id,case_id,member_id,family_id,patient_name,patient_dob,patient_state_code,patient_district_code,patient_district_name,...,m_flag,careplan_desc,discharge_type,admission_type,claim_approved_date,last_insert_dt,admission_dt,only_date,temp_date,preauth_hour
3,1764602,1015568572,BOCW/BR/2025/R2/1015568572,MQPWPFNQW,10BO102260135880135810016910,Radhika Devi,1995,10,207,MUNGER,...,None,None,nan,P,2025-11-07 16:01:01.663000,2025-11-09 22:20:02.947000,2025-10-21 00:00:00,2025-10-21,2025-10-21,14
20,1764619,1014992144,PMJAY/BR/S/G/2025/R2/1014992144,MLF74R6DC,10AAY10030050002001300058,NARESH PASWAN,1993,10,220,SHEOHAR,...,None,None,nan,P,2025-11-08 22:14:03.083000,2025-11-08 22:20:03.246000,2025-10-08 17:01:00,2025-10-08,2025-10-08,23
27,1764626,1015215111,PMJAY/BR/S/G/2025/R2/1015215111,PZPTK6OW2,10PH10100040174041700026,Sabina Khatoon,1991,10,201,KATIHAR,...,None,None,nan,P,2025-11-08 15:13:47.030000,2025-11-08 15:20:04.198000,2025-10-13 13:34:00,2025-10-14,2025-10-14,11
63,1764662,1015616229,PMJAY/BR/S/G/2025/R2/1015616229,MLDWMCKXW,10AAY10280150002002000057,Samti Devi,1991,10,212,PATNA,...,None,None,nan,P,NaT,2025-11-09 14:00:03.544000,2025-10-22 17:30:00,2025-10-22,2025-10-22,17
111,1764710,1015975085,PMJAY/BR/S/G/2025/R2/1015975085,MMIBEL2YA,10PH10110050002004000017,SARITA KUMARI,2010,10,205,MADHEPURA,...,None,None,nan,P,2025-11-08 22:13:45.886000,2025-11-08 22:20:03.246000,2025-10-29 00:00:00,2025-10-30,2025-10-30,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91070,1855669,1015523187,PMJAY/BR/S/G/2025/R2/1015523187,ML7UWUR69,10PH102300141524629200001034,AJIT KUMAR,1988,10,212,PATNA,...,None,None,nan,P,2025-11-01 22:32:31.347000,2025-11-03 17:20:03.577000,2025-10-19 00:00:00,2025-10-19,2025-10-19,18
92072,1856671,1015553388,PMJAY/BR/S/G/2025/R2/1015553388,MS1IC20EX,10PH102280137724404800000228,Guddi Kumari,1993,10,219,SHEIKHPURA,...,None,None,nan,P,2025-11-02 22:15:24.300000,2025-11-03 17:20:03.577000,2025-10-21 11:06:00,2025-10-21,2025-10-21,11
92090,1856689,1015553752,PMJAY/BR/S/G/2025/R2/1015553752,MS46HLYRW,10PH102070108822011100000410,Sanjeev Kumar Nirala,1992,10,206,MADHUBANI,...,None,None,nan,P,NaT,2025-10-22 19:40:02.501000,2025-10-21 13:00:00,2025-10-22,2025-10-22,19
92170,1856769,1015555112,PMJAY/BR/S/G/2025/R2/1015555112,MQPKT0RBX,10PH10140070154054210139,Md Tanweer Alam,1994,10,208,MUZAFFARPUR,...,None,None,nan,P,2025-11-04 11:36:38.317000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-21,2025-10-21,11
93010,1857609,1015568963,PMJAY/BR/S/G/2025/R2/1015568963,MS43W9BKJ,10PH10170120017004500009,Manejar Ray,1990,10,218,SARAN,...,None,None,nan,P,2025-11-05 19:13:55.632000,2025-11-05 19:20:03.212000,2025-10-21 00:00:00,2025-10-23,2025-10-23,14

In [20]:
df1[(df1['hospital_type'] == 'P') & (df1['procedure_code'].str.contains('SE', na=False)) & (df1['age'] < 40)]

,id,registration_id,case_id,member_id,family_id,patient_name,patient_dob,patient_state_code,patient_district_code,patient_district_name,...,m_flag,careplan_desc,discharge_type,admission_type,claim_approved_date,last_insert_dt,admission_dt,only_date,temp_date,preauth_hour
3,1764602,1015568572,BOCW/BR/2025/R2/1015568572,MQPWPFNQW,10BO102260135880135810016910,Radhika Devi,1995,10,207,MUNGER,...,None,None,nan,P,2025-11-07 16:01:01.663000,2025-11-09 22:20:02.947000,2025-10-21 00:00:00,2025-10-21,2025-10-21,14
20,1764619,1014992144,PMJAY/BR/S/G/2025/R2/1014992144,MLF74R6DC,10AAY10030050002001300058,NARESH PASWAN,1993,10,220,SHEOHAR,...,None,None,nan,P,2025-11-08 22:14:03.083000,2025-11-08 22:20:03.246000,2025-10-08 17:01:00,2025-10-08,2025-10-08,23
27,1764626,1015215111,PMJAY/BR/S/G/2025/R2/1015215111,PZPTK6OW2,10PH10100040174041700026,Sabina Khatoon,1991,10,201,KATIHAR,...,None,None,nan,P,2025-11-08 15:13:47.030000,2025-11-08 15:20:04.198000,2025-10-13 13:34:00,2025-10-14,2025-10-14,11
63,1764662,1015616229,PMJAY/BR/S/G/2025/R2/1015616229,MLDWMCKXW,10AAY10280150002002000057,Samti Devi,1991,10,212,PATNA,...,None,None,nan,P,NaT,2025-11-09 14:00:03.544000,2025-10-22 17:30:00,2025-10-22,2025-10-22,17
111,1764710,1015975085,PMJAY/BR/S/G/2025/R2/1015975085,MMIBEL2YA,10PH10110050002004000017,SARITA KUMARI,2010,10,205,MADHEPURA,...,None,None,nan,P,2025-11-08 22:13:45.886000,2025-11-08 22:20:03.246000,2025-10-29 00:00:00,2025-10-30,2025-10-30,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91070,1855669,1015523187,PMJAY/BR/S/G/2025/R2/1015523187,ML7UWUR69,10PH102300141524629200001034,AJIT KUMAR,1988,10,212,PATNA,...,None,None,nan,P,2025-11-01 22:32:31.347000,2025-11-03 17:20:03.577000,2025-10-19 00:00:00,2025-10-19,2025-10-19,18
92072,1856671,1015553388,PMJAY/BR/S/G/2025/R2/1015553388,MS1IC20EX,10PH102280137724404800000228,Guddi Kumari,1993,10,219,SHEIKHPURA,...,None,None,nan,P,2025-11-02 22:15:24.300000,2025-11-03 17:20:03.577000,2025-10-21 11:06:00,2025-10-21,2025-10-21,11
92090,1856689,1015553752,PMJAY/BR/S/G/2025/R2/1015553752,MS46HLYRW,10PH102070108822011100000410,Sanjeev Kumar Nirala,1992,10,206,MADHUBANI,...,None,None,nan,P,NaT,2025-10-22 19:40:02.501000,2025-10-21 13:00:00,2025-10-22,2025-10-22,19
92170,1856769,1015555112,PMJAY/BR/S/G/2025/R2/1015555112,MQPKT0RBX,10PH10140070154054210139,Md Tanweer Alam,1994,10,208,MUZAFFARPUR,...,None,None,nan,P,2025-11-04 11:36:38.317000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-21,2025-10-21,11
93010,1857609,1015568963,PMJAY/BR/S/G/2025/R2/1015568963,MS43W9BKJ,10PH10170120017004500009,Manejar Ray,1990,10,218,SARAN,...,None,None,nan,P,2025-11-05 19:13:55.632000,2025-11-05 19:20:03.212000,2025-10-21 00:00:00,2025-10-23,2025-10-23,14

In [21]:
df1[(df1['hospital_type'] == 'P') & (df1['procedure_code'].str.contains('SE', na=False)) & ((df1['preauth_hour'] < 8) | (df1['preauth_hour'] >= 18))]

,id,registration_id,case_id,member_id,family_id,patient_name,patient_dob,patient_state_code,patient_district_code,patient_district_name,...,m_flag,careplan_desc,discharge_type,admission_type,claim_approved_date,last_insert_dt,admission_dt,only_date,temp_date,preauth_hour
19,1764618,1014983703,PMJAY/BR/S/G/2025/R2/1014983703,MES6UN5J0,10AAY10090030028030300084,JULEKHA,1965,10,214,PURNIA,...,None,None,nan,P,2025-11-08 22:14:03.559000,2025-11-08 22:20:03.246000,2025-10-08 00:00:00,2025-10-08,2025-10-08,18
20,1764619,1014992144,PMJAY/BR/S/G/2025/R2/1014992144,MLF74R6DC,10AAY10030050002001300058,NARESH PASWAN,1993,10,220,SHEOHAR,...,None,None,nan,P,2025-11-08 22:14:03.083000,2025-11-08 22:20:03.246000,2025-10-08 17:01:00,2025-10-08,2025-10-08,23
110,1764709,1015972930,PMJAY/BR/S/G/2025/R2/1015972930,MKOTL3FOY,10PH10050080037021600033,SITA DEVI,1961,10,206,MADHUBANI,...,None,None,nan,P,2025-11-09 22:09:05.463000,2025-11-09 22:00:05.046000,2025-10-29 21:00:00,2025-10-29,2025-10-29,22
125,1764724,1016021295,PMJAY/BR/S/G/2025/R2/1016021295,PQZE1FXAM,10PH10270020001000220135,Mamta Devi,1991,10,209,NALANDA,...,None,None,nan,P,2025-11-09 17:29:30.471000,2025-11-09 17:20:03.081000,2025-10-30 00:00:00,2025-10-30,2025-10-30,18
128,1764727,1016028950,PMJAY/BR/S/G/2025/R2/1016028950,PEXB3EUBE,10PH10320110255042820016,Parwati Devi,1994,10,215,ROHTAS,...,None,None,nan,P,2025-11-08 15:13:47.338000,2025-11-08 15:20:04.198000,2025-10-30 00:00:00,2025-10-31,2025-10-31,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93361,1857960,1015574943,PMJAY/BR/S/G/2025/R2/1015574943,ML5YRV2M1,10PH10320100001000300038,Ram Payare Sharma,1953,10,215,ROHTAS,...,None,None,nan,P,2025-11-04 11:34:19.923000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22,4
93367,1857966,1015575014,PMJAY/BR/S/G/2025/R2/1015575014,MQLVZ3BOY,10PH10020200009007010141,Pundev Ray,1971,10,213,PURBI CHAMPARAN,...,None,None,nan,P,2025-11-04 11:33:28.367000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22,5
93373,1857972,1015575161,PMJAY/BR/S/G/2025/R2/1015575161,MLHDVCY9E,10PH102310142924727100000211,BABAN SHARMA,1957,10,193,BHOJPUR,...,None,None,nan,P,2025-11-04 11:33:33.241000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22,5
93380,1857979,1015575263,PMJAY/BR/S/G/2025/R2/1015575263,MEP76YS0G,10PH10180110125030200091,Janki Devi,1953,10,224,VAISHALI,...,None,None,nan,P,2025-11-04 11:37:33.151000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22,4
93395,1857994,1015575441,PMJAY/BR/S/G/2025/R2/1015575441,MK1GR7Z2W,10PH10180110130031200049,Nagdev Ray,1953,10,224,VAISHALI,...,None,None,nan,P,2025-11-04 11:34:24.841000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22,4

In [22]:
df1[(df1['hospital_type'] == 'P') & (df1['category_details'].str.contains('Opthalmology', na=False)) & ((df1['preauth_hour'] < 8) | (df1['preauth_hour'] >= 18))]

,id,registration_id,case_id,member_id,family_id,patient_name,patient_dob,patient_state_code,patient_district_code,patient_district_name,...,m_flag,careplan_desc,discharge_type,admission_type,claim_approved_date,last_insert_dt,admission_dt,only_date,temp_date,preauth_hour
19,1764618,1014983703,PMJAY/BR/S/G/2025/R2/1014983703,MES6UN5J0,10AAY10090030028030300084,JULEKHA,1965,10,214,PURNIA,...,None,None,nan,P,2025-11-08 22:14:03.559000,2025-11-08 22:20:03.246000,2025-10-08 00:00:00,2025-10-08,2025-10-08,18
20,1764619,1014992144,PMJAY/BR/S/G/2025/R2/1014992144,MLF74R6DC,10AAY10030050002001300058,NARESH PASWAN,1993,10,220,SHEOHAR,...,None,None,nan,P,2025-11-08 22:14:03.083000,2025-11-08 22:20:03.246000,2025-10-08 17:01:00,2025-10-08,2025-10-08,23
110,1764709,1015972930,PMJAY/BR/S/G/2025/R2/1015972930,MKOTL3FOY,10PH10050080037021600033,SITA DEVI,1961,10,206,MADHUBANI,...,None,None,nan,P,2025-11-09 22:09:05.463000,2025-11-09 22:00:05.046000,2025-10-29 21:00:00,2025-10-29,2025-10-29,22
125,1764724,1016021295,PMJAY/BR/S/G/2025/R2/1016021295,PQZE1FXAM,10PH10270020001000220135,Mamta Devi,1991,10,209,NALANDA,...,None,None,nan,P,2025-11-09 17:29:30.471000,2025-11-09 17:20:03.081000,2025-10-30 00:00:00,2025-10-30,2025-10-30,18
128,1764727,1016028950,PMJAY/BR/S/G/2025/R2/1016028950,PEXB3EUBE,10PH10320110255042820016,Parwati Devi,1994,10,215,ROHTAS,...,None,None,nan,P,2025-11-08 15:13:47.338000,2025-11-08 15:20:04.198000,2025-10-30 00:00:00,2025-10-31,2025-10-31,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93361,1857960,1015574943,PMJAY/BR/S/G/2025/R2/1015574943,ML5YRV2M1,10PH10320100001000300038,Ram Payare Sharma,1953,10,215,ROHTAS,...,None,None,nan,P,2025-11-04 11:34:19.923000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22,4
93367,1857966,1015575014,PMJAY/BR/S/G/2025/R2/1015575014,MQLVZ3BOY,10PH10020200009007010141,Pundev Ray,1971,10,213,PURBI CHAMPARAN,...,None,None,nan,P,2025-11-04 11:33:28.367000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22,5
93373,1857972,1015575161,PMJAY/BR/S/G/2025/R2/1015575161,MLHDVCY9E,10PH102310142924727100000211,BABAN SHARMA,1957,10,193,BHOJPUR,...,None,None,nan,P,2025-11-04 11:33:33.241000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22,5
93380,1857979,1015575263,PMJAY/BR/S/G/2025/R2/1015575263,MEP76YS0G,10PH10180110125030200091,Janki Devi,1953,10,224,VAISHALI,...,None,None,nan,P,2025-11-04 11:37:33.151000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22,4
93395,1857994,1015575441,PMJAY/BR/S/G/2025/R2/1015575441,MK1GR7Z2W,10PH10180110130031200049,Nagdev Ray,1953,10,224,VAISHALI,...,None,None,nan,P,2025-11-04 11:34:24.841000,2025-11-04 11:40:02.738000,2025-10-21 00:00:00,2025-10-22,2025-10-22,4

In [37]:
def calculate_ot_violations(df_cases, df_hospitals):
    """
    Replicates OT overload logic exactly as in load_dataframes().

    Parameters
    ----------
    df_cases : DataFrame
        From pmjay_fraud_dashboard_app_last24hour
        Must contain:
          - hospital_id
          - preauth_init_date (datetime)
    
    df_hospitals : DataFrame
        From pmjay_fraud_dashboard_app_hospital_beds
        Must contain:
          - hospital_id
          - number_of_surgeons

    Returns
    -------
    df_cases_with_ot : DataFrame
        Original df_cases with a new boolean column 'ot_violation'
    """

    df = df_cases.copy()

    # -----------------------------------
    # Step 1: Build capacity map
    # capacity = number_of_surgeons * 30
    # -----------------------------------
    capacity_map = (
        df_hospitals
        .dropna(subset=['number_of_surgeons'])
        .assign(capacity=lambda x: x['number_of_surgeons'] * 30)
        .set_index('hospital_id')['capacity']
        .to_dict()
    )

    # -----------------------------------
    # Step 2: Sort cases by hospital + time
    # -----------------------------------
    df['preauth_init_date'] = pd.to_datetime(
        df['preauth_init_date'],
        format='mixed',
        errors='coerce'
    )

    # df = df.sort_values(
    #     by=['hospital_id', 'preauth_init_date'],
    #     ascending=[True, True]
    # )

    df = df.sort_values(by=['preauth_init_date'], ascending=True)
    df_ot_case = df.groupby('hospital_id')
    # -----------------------------------
    # Step 3: Running count per hospital
    # -----------------------------------
    df_ot_case['hospital_running_count'] = (
        df.groupby('hospital_id').cumcount() + 1
    )

    # -----------------------------------
    # Step 4: Flag OT violations
    # -----------------------------------
    def is_ot_violation(row):
        cap = capacity_map.get(row['hospital_id'])
        if cap is None:
            return False
        return row['hospital_running_count'] > cap

    df['ot_violation'] = df.apply(is_ot_violation, axis=1)

    return df

In [38]:
# Load hospital beds table
hospital_df = pd.read_sql_query(
    'SELECT * FROM pmjay_fraud_dashboard_app_hospitalbeds',
    conn
)

# Apply OT logic
df_with_ot = calculate_ot_violations(df1, hospital_df)

# Inspect violations
df_with_ot[df_with_ot['ot_violation'] == True]

TypeError: 'DataFrameGroupBy' object does not support item assignment

In [26]:
target_categories = [
    "Opthalmology", 
    "Opthalmology|Opthalmology", 
    "Opthalmology|Opthalmology|Opthalmology",
    "Otorhinolaryngology|Otorhinolaryngology|Otorhinolaryngology",
    "General Surgery|General Surgery",
    "Opthalmology|Opthalmology|Opthalmology|Opthalmology",
    "General Surgery|General Surgery|General Surgery",
    "General Surgery|Otorhinolaryngology|Otorhinolaryngology",
    "Medical Oncology",
    "Otorhinolaryngology|Otorhinolaryngology|Otorhinolaryngology|Otorhinolaryngology"
]

optha_df = df1[df1['category_details'].isin(target_categories)]
opt = optha_df[(optha_df['hospital_type'] == 'P')]
opt['preauth_date'] = pd.to_datetime(opt['preauth_init_date'], format='mixed').dt.date
optha = opt.groupby(['hospital_id', 'preauth_date']).size().reset_index(name='counts')
optha[optha['counts'] > 30]['hospital_id'].nunique()

/var/folders/8x/2x087_p92nl_024bbj2_6q8c0000gq/T/ipykernel_79832/2955367186.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  opt['preauth_date'] = pd.to_datetime(opt['preauth_init_date'], format='mixed').dt.date

39

In [27]:
df1['preauth_init_date']

0       2025-10-04 11:11:36.787
1       2025-10-13 12:19:52.346
2       2025-10-18 17:22:20.695
3       2025-10-21 14:35:16.250
4       2025-10-22 19:41:21.294
                  ...
93395   2025-10-22 04:21:16.093
93396   2025-10-22 12:12:52.116
93397   2025-10-21 16:42:21.363
93398   2025-10-22 13:17:47.043
93399   2025-10-23 15:13:40.000
Name: preauth_init_date, Length: 93400, dtype: datetime64[ns]

In [ ]:
df5 = pd.read_excel("ophthalmology_all_2025-01-10_to_2026-01-10.xlsx")
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24635 entries, 0 to 24634
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   S.No           24635 non-null  int64
 1   Claim ID       24635 non-null  int64
 2   Patient Name   24635 non-null  object
 3   District       24635 non-null  object
 4   Hospital ID    24635 non-null  object
 5   Hospital Name  24635 non-null  object
 6   Amount         24635 non-null  float64
 7   Preauth Time   24635 non-null  object
 8   Age > 40       749 non-null    object
 9   OT Cases       21914 non-null  object
 10  Pre-auth Out   8678 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 2.1+ MB

In [ ]:
df5[df5['OT Cases'] == 'OT']['Hospital ID'].value_counts()

Hospital ID
HOSP10P24718     3556
HOSP10P61188      871
HOSP10P115202     866
HOSP10P07435      738
HOSP10P158442     555
                 ...
HOSP10P00538        3
HOSP10P11632        2
HOSP10P71952        1
HOSP10P02532        1
HOSP10P159203       1
Name: count, Length: 110, dtype: int64

In [ ]:
df1[df1['registration_id'].isin(df5['Claim ID'].astype(str))]['category_details'].value_counts()

category_details
Opthalmology                                                                       23846
Opthalmology|Opthalmology                                                            764
Opthalmology|Opthalmology|Opthalmology                                                 9
Otorhinolaryngology|Otorhinolaryngology|Otorhinolaryngology                            7
General Surgery|General Surgery                                                        3
General Surgery|General Surgery|General Surgery                                        2
General Surgery|Otorhinolaryngology|Otorhinolaryngology                                1
Medical Oncology                                                                       1
Opthalmology|Opthalmology|Opthalmology|Opthalmology                                    1
Otorhinolaryngology|Otorhinolaryngology|Otorhinolaryngology|Otorhinolaryngology        1
Name: count, dtype: int64

### Hospital cases

In [ ]:
df6 = pd.read_excel("hospital_bed_cases.xlsx")
df6

,S.No,Hospital ID,Hospital Name,District,State,Bed Capacity,Admissions,Excess,Last Violation
0,1,HOSP10P04249,AKHILESHWARI DANTCHIKITSALY,SARAN,BIHAR,12,19,7,2025-10-12
1,2,HOSP10P04249,AKHILESHWARI DANTCHIKITSALY,SARAN,BIHAR,12,20,8,2025-10-18
2,3,HOSP10P04719,B. S. L. EYE CARE,BHOJPUR,BIHAR,12,15,3,2025-10-14
3,4,HOSP10P07282,SATYABHAMA NETHRALAYA,KATIHAR,BIHAR,12,14,2,2025-10-04
4,5,HOSP10P07282,SATYABHAMA NETHRALAYA,KATIHAR,BIHAR,12,31,19,2025-10-06
...,...,...,...,...,...,...,...,...,...
234,235,HOSP10P99584,Harishakha Drishti,SHEIKHPURA,BIHAR,10,15,5,2025-10-09
235,236,HOSP10P99584,Harishakha Drishti,SHEIKHPURA,BIHAR,10,17,7,2025-10-10
236,237,HOSP10P99584,Harishakha Drishti,SHEIKHPURA,BIHAR,10,16,6,2025-10-11
237,238,HOSP10P99584,Harishakha Drishti,SHEIKHPURA,BIHAR,10,19,9,2025-10-15
238,239,HOSP10P99584,Harishakha Drishti,SHEIKHPURA,BIHAR,10,11,1,2025-10-17

In [ ]:
df7 = pd.read_excel("HOSPITAL_BEDS.xlsx")
df7['hospital_id'] = df7['Hospital ID']
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1039 entries, 0 to 1038
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Hospital Name       1039 non-null   object
 1   Hospital ID         1039 non-null   object
 2   Bed Strength        985 non-null    float64
 3   Number of Surgeons  1039 non-null   int64
 4   Number of OT        1039 non-null   int64
 5   hospital_id         1039 non-null   object
dtypes: float64(1), int64(2), object(3)
memory usage: 48.8+ KB

In [ ]:
df1['admission_date'] = pd.to_datetime(df1['admission_dt'], format='mixed').dt.date
opthha_7 = df1[(df1['hospital_type'] == 'P') & (df1['procedure_code'].str.contains('SE', na=False))]
optha_8 = opthha_7.groupby(['hospital_id', 'admission_date']).size().reset_index(name='counts')
enriched_df = pd.merge(
    optha_8, 
    df7, 
    on='hospital_id', 
    how='left'
)
enriched_df[enriched_df['counts'] > enriched_df['Bed Strength']]

,hospital_id,admission_date,counts,Hospital Name,Hospital ID,Bed Strength,Number of Surgeons,Number of OT
23,HOSP10P00416,2025-10-18,13,Nayansukh Netralya Llp,HOSP10P00416,12.0,1.0,1.0
32,HOSP10P00621,2025-10-04,11,Asg Hospital Pvt Ltd,HOSP10P00621,10.0,1.0,1.0
33,HOSP10P00621,2025-10-05,11,Asg Hospital Pvt Ltd,HOSP10P00621,10.0,1.0,1.0
34,HOSP10P00621,2025-10-06,18,Asg Hospital Pvt Ltd,HOSP10P00621,10.0,1.0,1.0
35,HOSP10P00621,2025-10-07,24,Asg Hospital Pvt Ltd,HOSP10P00621,10.0,1.0,1.0
...,...,...,...,...,...,...,...,...
2176,HOSP10P99584,2025-10-18,15,Harishakha Drishthi,HOSP10P99584,10.0,1.0,1.0
2177,HOSP10P99584,2025-10-21,19,Harishakha Drishthi,HOSP10P99584,10.0,1.0,1.0
2179,HOSP10P99584,2025-10-29,55,Harishakha Drishthi,HOSP10P99584,10.0,1.0,1.0
2180,HOSP10P99584,2025-10-30,12,Harishakha Drishthi,HOSP10P99584,10.0,1.0,1.0
2181,HOSP10P99584,2025-10-31,14,Harishakha Drishthi,HOSP10P99584,10.0,1.0,1.0